permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: true
url: "http://datavalley.github.io"
kramdown:
  input: GFM

# 作者信息
author: 
  name: zmz
  email: zmz@mail.dlut.edu.cn
  link: http://datavalley.github.io

# 站点信息
title: 小z的博客 
description: 小z的博客
url: http://datavalley.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /img/hello.jpg
favicon: http://datavalley.github.io/img/hello.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: datavalley.github.io

# disqus 设置
disqus:
  shortname: datavalley
