permalink: /:year/:month/:day/:title.html
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
url: "http://datavalley.github.io"

# 作者信息
author: 
  name: zmz
  email: zmz@mail.dlut.edu.cn
  link: http://datavalley.github.io

# 站点信息
title: 数据谷
description: 小z的博客
url: http://datavalley.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /img/logo.jpg
favicon: http://datavalley.github.io/img/logo.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: datavalley.github.io

# disqus 设置
disqus:
  shortname: datavalley
